# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


## Custom Setup

# git 
source ~/git-completion.bash 
export PS1='\[\e[36;1m\]\u@\[\e[32;1m\]\H:\[\e[0m\]\W\[\e[31;1m\]$(__git_ps1 "(\%s)")\[\e[0m\]>' 
export GIT_SSL_NO_VERIFY=1

git config --global --replace-all  user.name "Daehyung Park"
#git config --global user.email "daehyung@csail.mit.edu"

# Custom 
#export DISPLAY=:0.0
export ROS_MASTER_URI=http://localhost:11311

## some more aliases -------------------------------------------
# location
alias aa='cd /home/daehyung/git/development/cs592_sol_ws/src/cs592_RLI_sol/assignment_2'
alias ss='source ./robot.sh sim'
alias gg='git commit -a -m "test" && git push'

alias hawk='ssh -X daehyung@143.248.139.11'
alias dell2='ssh dpark@128.31.37.29'

export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH


if [ "$HOSTNAME" = pidi ] ; then
   export LD_LIBRARY_PATH=$(openrave-config --python-dir)/openravepy/_openravepy_:$LD_LIBRARY_PATH
   export PYTHONPATH=$(openrave-config --python-dir)/openravepy/_openravepy_:/home/dpark/git/external/trajopt:/home/dpark/git/external/trajopt/build_trajopt/lib:$PYTHONPATH
fi
if [ "$HOSTNAME" = gram ] ; then
   export LD_LIBRARY_PATH=/home/daehyung/.mujoco/mujoco210/bin:$LD_LIBRARY_PATH
   #export PYTHONPATH=/home/daehyung/.local/lib:$PYTHONPATH
fi
if [ "$HOSTNAME" = hawk ] ; then
   # >>> conda initialize >>>
   # !! Contents within this block are managed by 'conda init' !!
   #__conda_setup="$('/home/daehyung/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
   #if [ $? -eq 0 ]; then
   #    eval "$__conda_setup"
   #else
   #   if [ -f "/home/daehyung/anaconda3/etc/profile.d/conda.sh" ]; then
   #     . "/home/daehyung/anaconda3/etc/profile.d/conda.sh"
   #   else      
   #     export PATH="/home/daehyung/anaconda3/bin:$PATH"
   #   fi
   #fi
   #unset __conda_setup
   # <<< conda initialize <<<
   #source /home/daehyung/.local/bin/virtualenvwrapper.sh
   cd
fi


# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"


# For ROS
alias noetic="source /opt/ros/noetic/setup.bash; export ROS_PYTHON_VERSION=2; echo \"Noetic is Activated!\""
alias foxy="source /opt/ros/foxy/setup.bash; ROS_VERSION=2; export ROS_PYTHON_VERSION=3; echo \"Foxy is Activated!\""
export ROBOT=sim

#export ROS_MASTER_URI=http://192.168.0.3:11311
#export ROS_IP=192.168.0.4
#export ROS_MASTER_URI=http://192.168.1.50:11311
#export ROS_IP=192.168.1.5
#unset ROS_PACKAGE_PATH && unset ROS_ETC_DIR && unset ROS_ROOT

# For ROS2
export ROS_DOMAIN_ID=10
source /usr/share/colcon_cd/function/colcon_cd.sh
export _colcon_cd_root=/opt/ros/foxy/
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

alias cba='colcon build --symlink-install'
alias ccc='colcon build --symlink-install && source ./install/local_setup.bash'
alias cbp='colcon build --symlink-install --packages-select'
alias cbu='colcon build --symlink-install --packages-up-to'

alias rt='ros2 topic list'
alias re='ros2 topid echo'
alias rn='ros2 node list'

alias aa='cd git/development/manipulation_ws'
